// 公共
export const COMMON_LOADING_STATUS = 'COMMON_LOADING_STATUS'
export const COMMON_TOGGLE_TIPS_STATUS = 'COMMON_TOGGLE_TIPS_STATUS'

export const GET_MESSAGE_SYS_LIST = 'GET_MESSAGE_SYS_LIST'
export const GET_MESSAGE_APP_LIST = 'GET_MESSAGE_APP_LIST'


export const GET_CIRCLES_RECOMMEND_LIST = 'GET_CIRCLES_RECOMMEND_LIST'
export const GET_CIRCLES_HOT_LIST = 'GET_CIRCLES_HOT_LIST'
export const GET_CIRCLES_NEAR_LIST = 'GET_CIRCLES_NEAR_LIST'

export const GET_CIRCLES_YZ_LIST = 'GET_CIRCLES_YZ_LIST'
export const GET_CIRCLES_FRIEND_LIST = 'GET_CIRCLES_FRIEND_LIST'
export const GET_CIRCLES_DETAIL = 'GET_CIRCLES_DETAIL'


export const GET_ARTICLE_CATEGORY_LIST = 'GET_ARTICLE_CATEGORY_LIST'
export const GET_ARTICLE_LIST = 'GET_ARTICLE_LIST'
export const GET_ARTICLE_DETAIL = 'GET_ARTICLE_DETAIL'


export const GET_ACTIVITY_LIST = 'GET_ACTIVITY_LIST'
export const GET_ACTIVITY_OFFICIAL_LIST = 'GET_ACTIVITY_OFFICIAL_LIST'
export const GET_ACTIVITY_DETAIL = 'GET_ACTIVITY_DETAIL'

// export const GET_CIRCLES_YZ_LIST = 'GET_CIRCLES_YZ_LIST'
// export const GET_CIRCLES_YZ_LIST = 'GET_CIRCLES_YZ_LIST'
// export const GET_CIRCLES_YZ_LIST = 'GET_CIRCLES_YZ_LIST'
// export const GET_CIRCLES_YZ_LIST = 'GET_CIRCLES_YZ_LIST'
// export const GET_CIRCLES_YZ_LIST = 'GET_CIRCLES_YZ_LIST'
// export const GET_CIRCLES_YZ_LIST = 'GET_CIRCLES_YZ_LIST'