// 公共
export const COMMON_LOADING_STATUS = 'COMMON_LOADING_STATUS'
export const COMMON_TOGGLE_TIPS_STATUS = 'COMMON_TOGGLE_TIPS_STATUS'





export const GET_MESSAGE_LIST = 'GET_MESSAGE_LIST'



export const GET_CIRCLES_RECOMMEND_LIST = 'GET_CIRCLES_RECOMMEND_LIST'
export const GET_CIRCLES_HOT_LIST = 'GET_CIRCLES_HOT_LIST'
export const GET_CIRCLES_NEAR_LIST = 'GET_CIRCLES_NEAR_LIST'

export const GET_CIRCLES_YZ_LIST = 'GET_CIRCLES_YZ_LIST'


export const GET_ARTICLE_CATEGORY_LIST = 'GET_ARTICLE_CATEGORY_LIST'
export const GET_ARTICLE_LIST = 'GET_ARTICLE_LIST'
export const GET_ARTICLE_DETAIL = 'GET_ARTICLE_DETAIL'

// export const GET_CIRCLES_YZ_LIST = 'GET_CIRCLES_YZ_LIST'
// export const GET_CIRCLES_YZ_LIST = 'GET_CIRCLES_YZ_LIST'
// export const GET_CIRCLES_YZ_LIST = 'GET_CIRCLES_YZ_LIST'
// export const GET_CIRCLES_YZ_LIST = 'GET_CIRCLES_YZ_LIST'
// export const GET_CIRCLES_YZ_LIST = 'GET_CIRCLES_YZ_LIST'
// export const GET_CIRCLES_YZ_LIST = 'GET_CIRCLES_YZ_LIST'
// export const GET_CIRCLES_YZ_LIST = 'GET_CIRCLES_YZ_LIST'
// export const GET_CIRCLES_YZ_LIST = 'GET_CIRCLES_YZ_LIST'
// export const GET_CIRCLES_YZ_LIST = 'GET_CIRCLES_YZ_LIST'
// export const GET_CIRCLES_YZ_LIST = 'GET_CIRCLES_YZ_LIST'
// export const GET_CIRCLES_YZ_LIST = 'GET_CIRCLES_YZ_LIST'